ejemplobasedijango/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    path('',include('home.urls')),
    path('polls/', include('polls.urls')),
    #path('', include('libros.urls')),
    #path('biblioteca/', include('biblioteca.urls')),
    path('admin/', admin.site.urls),
    #path('mongodb/', include('mongodbapp.urls')),
    #path('rest-auth/', include('rest_auth.urls')),
    #url(r'^', include('restexample.urls')),
    #path('', include('restexample.urls')),


]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#from libros.scaffolding import LibroCrudManager # or from views import BookCrudManager depending on where you've put it
#book_crud = LibroCrudManager()
#urlpatterns += book_crud.get_url_patterns()

home/urls.py
from django.urls import path

from . import views
app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/<int:n>', views.detail, name='detail'),
    path('home/json', views.devuelveJson, name='devuelvejson'),
    path('home/sendjson', views.SendJson, name='sendjson'),
    path('home/sendForm', views.sendForm, name='sendform'),
    path('home/<str:nombre>', views.nombre, name='nombre'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/base.html
{% load staticfiles %}<!DOCTYPE html>
    <html>
        <head>
            <title>Ejemplo de CRUD de Géneros Literarios</title>
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
            <!--link rel="stylesheet" href="{% static 'css/blog.css' %}"-->
        </head>
        <body>
            <div class="page-header">
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">Gestión de Biblioteca</a>
                    </div>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'home:index' %}" class="active">Home</a></li>
                        <li><a href="/home/2">Enlace con numero</a></li>
                        <li><a href="{% url 'home:detail' 2 %}">Enlace con numero v2</a></li>
                        <li><a href="/home/pepe">Enlace con nombre</a></li>
                        <li><a href="{% url 'home:nombre' 'pepe' %}">Enlace con nombre v2</a></li>
                        <li><a href="{% url 'polls:index' %}">Polls</a></li>
                    </ul>
                      <ul class="nav navbar-nav">
                        <!-- Cambiar a un enlace nombrado por urls -->
                        <li><a href="/libros">Libros</a></li>
                        <li><a href="{% url 'genre-list' %}">Biblioteca</a></li>

                        <li><a href="{% url 'genre-list2' %}">Biblioteca DataTable</a></li>
                        <li><a href="{% url 'genre-list3' %}">Listado de Géneros</a></li>
                        <li><a href="{% url 'home:devuelvejson' %}">Devuelve JSON</a></li>
                        <li><a href="{% url 'tool-list' %}">Listado de Posts</a></li>
                    </ul>
                  </div>
                </nav>
            </div>
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                    {% block content %}
                    {% endblock %}
                    </div>
                </div>
            </div>
        </body>
    </html>